# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Evaluate_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

## FOR FRAMELESS WINDOWS
from PyQt5.QtCore import Qt


## FOR SHORTCUT 
from PyQt5.QtWidgets  import QShortcut
from PyQt5.QtGui import QKeySequence

## TO RAISE ERRORS OR SHOW DATA 
from PopUpBox_window import Ui_Form as dialog_box

## For Database connectivity
import sqlite3

class Ui_Form(object):
    def __init__(self):
        ''' VARIBLES INITIALISATION'''
        self.name,self.players,self.points = [],[],[]
        self.total_score = 0  


    #/////////////////////*********************QT DISGNER GENERATED**************************/////////////////////////////////
    #/////------START----------//////(DONOT EDIT UNTIL YOU KNOW WHAT YOU ARE DOING )
    def setupUi(self, Form):
        ## Connecting database
        self.connect = sqlite3.connect('CricketFantasy.db2')
        self.cursor = self.connect.cursor()

        Form.setObjectName("Form")
        Form.resize(475, 504)
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.setWindowFlag(Qt.FramelessWindowHint)## The line to Remove the Title Bar
        self.LABEL_POINTS = QtWidgets.QLabel(Form)
        self.LABEL_POINTS.setGeometry(QtCore.QRect(260, 110, 58, 25))
        self.LABEL_POINTS.setStyleSheet("font: 14pt \"MV Boli\";")
        self.LABEL_POINTS.setObjectName("LABEL_POINTS")
        self.VALUE_POINTS = QtWidgets.QLabel(Form)
        self.VALUE_POINTS.setGeometry(QtCore.QRect(324, 112, 70, 25))
        self.VALUE_POINTS.setStyleSheet("font: 14pt \"MV Boli\";\n"
"color: rgb(110, 243, 255);")
        self.VALUE_POINTS.setObjectName("VALUE_POINTS")
        self.LABEL_PLAYERS = QtWidgets.QLabel(Form)
        self.LABEL_PLAYERS.setGeometry(QtCore.QRect(50, 110, 71, 25))
        self.LABEL_PLAYERS.setStyleSheet("font: 14pt \"MV Boli\";")
        self.LABEL_PLAYERS.setObjectName("LABEL_PLAYERS")
        self.CBOX_MATCH = QtWidgets.QComboBox(Form)
        self.CBOX_MATCH.setGeometry(QtCore.QRect(280, 60, 131, 26))
        self.CBOX_MATCH.setStyleSheet("font: 11pt \"MV Boli\";")
        self.CBOX_MATCH.setObjectName("CBOX_MATCH")
        self.CBOX_MATCH.addItem("")
        self.CBOX_MATCH.addItem("")
        self.CBOX_MATCH.addItem("")
        self.CBOX_MATCH.addItem("")
        self.CBOX_MATCH.addItem("")
        self.CBOX_TEAM = QtWidgets.QComboBox(Form)
        self.CBOX_TEAM.setGeometry(QtCore.QRect(40, 60, 131, 26))
        self.CBOX_TEAM.setStyleSheet("font: 11pt \"MV Boli\";")
        self.CBOX_TEAM.setObjectName("CBOX_TEAM")
        self.CBOX_TEAM.addItem("")
        self.LIST_PLAYERS = QtWidgets.QListWidget(Form)
        self.LIST_PLAYERS.setGeometry(QtCore.QRect(40, 140, 181, 281))
        self.LIST_PLAYERS.setStyleSheet("font: 14pt \"MV Boli\";")
        self.LIST_PLAYERS.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.LIST_PLAYERS.setObjectName("LIST_PLAYERS")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(10, 90, 451, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.line.setFont(font)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 10, 436, 51))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 14pt \"MV Boli\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.LIST_SCORE = QtWidgets.QListWidget(Form)
        self.LIST_SCORE.setGeometry(QtCore.QRect(261, 140, 181, 281))
        self.LIST_SCORE.setStyleSheet("font: 14pt \"MV Boli\";\n"
"color: rgb(110, 243, 255);")
        self.LIST_SCORE.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.LIST_SCORE.setObjectName("LIST_POINTS")
        self.BTN_SCORE = QtWidgets.QPushButton(Form)
        self.BTN_SCORE.setGeometry(QtCore.QRect(182, 440, 123, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BTN_SCORE.sizePolicy().hasHeightForWidth())
        self.BTN_SCORE.setSizePolicy(sizePolicy)
        self.BTN_SCORE.setStyleSheet("font: 12pt \"MV Boli\";")
        self.BTN_SCORE.setObjectName("BTN_SCORE")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        #/////------END----------//////(DONOT EDIT UNTIL YOU KNOW WHAT YOU ARE DOING )

        ## MAKING SHORTCUT FOR CLOSING WINDOW (ESC)
        QShortcut(QKeySequence('Esc'), Form).activated.connect(Form.close)
        """ RETRIVING TEAM NAMES AND ADDING TO COMBO BOX"""
        try:
            self.cursor.execute("SELECT DISTINCT NAME FROM TEAMS ;")
            X=self.cursor.fetchall()

            for i in X:
                self.CBOX_TEAM.addItem(i[0]) 
        except:pass
        """ TO SHOW SCORE """
        self.BTN_SCORE.clicked.connect(self.calculate)
    

        self.Form = Form
    def calculate(self):
        " TO ADD DATA TO LIST AND TO  CALCULATE THE SCORE  " 
        self.LIST_PLAYERS.clear()
        self.LIST_SCORE.clear()
        self.VALUE_POINTS.setText(str(0)) ## INIALISING THE LABEL POINTS WITH 0
        try:
            team=self.CBOX_TEAM.currentText()
            
            self.cursor.execute("SELECT PLAYERS,VALUE FROM TEAMS WHERE NAME = '"+team+"';")
            row=self.cursor.fetchall()[0]

            selected=row[0].split()
            self.LIST_PLAYERS.addItems(selected)

            points = 0 ## FOR TOTAL POINTS
            for i in  row[1].split():points += int(i) ## ADDING POINTS 
        
            self.VALUE_POINTS.setText(str(points)) ## DISPLAYING POINTS TO WINDOW
            
            teamttl=0 ## FOR TOTAL SCORE
            ## LOOP TO RETRIVE AND ADD DATA TO LIST OF EVERY PLAYER
            for i in range(self.LIST_PLAYERS.count()):
                ttl, batscore, bowlscore, fieldscore=0,0,0,0
                nm=self.LIST_PLAYERS.item(i).text()
                cursor=self.connect.execute("select * from match where player='"+nm+"';")
                row=cursor.fetchone()
                batscore=int(row[1]/2)
                if batscore>=50: batscore+=5
                if batscore>=100: batscore+=10
                if row[1]>0:
                    sr=row[1]/row[2]
                    if sr>=80 and sr<100: batscore+=2
                    if sr>=100:batscore+=4
                batscore=batscore+row[3]
                batscore=batscore+2*row[4]
                bowlscore=row[8]*10
                if row[8]>=3: bowlscore=bowlscore+5
                if row[8]>=5: bowlscore=bowlscore=bowlscore+10
                if row[7]>0:
                    er=6*row[7]/row[5]
                    if er<=2: bowlscore=bowlscore+10
                    if er>2 and er<=3.5: bowlscore=bowlscore+7
                    if er>3.5 and er<=4.5: bowlscore=bowlscore+4
                fieldscore=(row[9]+row[10]+row[11])*10            
                ttl=batscore+bowlscore+fieldscore
                teamttl=teamttl+ttl

                self.LIST_SCORE.addItem(str(ttl)) ## ADDING SCORE OF EACH PLAYER TO LIST
            
            self.Error("The Score is "+str(teamttl))
        except:
            self.Error("Select the team name") ## RAISE AN ERROR WHEN TEAM IS NOT SELECTED

    def Error(self,message):
        "TO RAISE ERRORS OR SHOW SCORE "
        self.func_widget = QtWidgets.QWidget()
        self.func_call = dialog_box()
        self.func_call.setupUi(self.func_widget,message)
        self.func_widget.show()
    #/////------START----------//////(DONOT EDIT UNTIL YOU KNOW WHAT YOU ARE DOING )
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.LABEL_POINTS.setText(_translate("Form", "Points"))
        self.VALUE_POINTS.setText(_translate("Form", "0"))
        self.LABEL_PLAYERS.setText(_translate("Form", "Players"))
        self.CBOX_TEAM.setItemText(0, _translate("Form", "Select Team"))
        self.label.setText(_translate("Form", "Evaluate the Performance of your Fantasy Team"))
        self.BTN_SCORE.setText(_translate("Form", "Calculate Score"))

        self.CBOX_MATCH.setItemText(0, _translate("Form", "Match1"))
        self.CBOX_MATCH.setItemText(1, _translate("Form", "Match2"))
        self.CBOX_MATCH.setItemText(2, _translate("Form", "Match3"))
        self.CBOX_MATCH.setItemText(3, _translate("Form", "Match4"))
        self.CBOX_MATCH.setItemText(4, _translate("Form", "Match5"))       





if __name__ == "__main__":

    
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QDialog()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
#/////------END----------//////(DONOT EDIT UNTIL YOU KNOW WHAT YOU ARE DOING )

 