# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_team.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
 
## FOR FRAMELESS WINDOWS
from PyQt5.QtCore import Qt

## ## TO SEND THE DATA TO MAIN WINDOW
from PyQt5.QtCore import pyqtSlot , pyqtSignal

## FOR SHORTCUT 
from PyQt5.QtWidgets  import QShortcut  
from PyQt5.QtGui import QKeySequence

## FOR RASING ERRORS
from PopUpBox_window import Ui_Form as dialog_box


class Ui_NEW_WIN(QtCore.QObject):
    ## object to send data 
    submitted = QtCore.pyqtSignal(str)
    #/////////////////////*********************QT DISGNER GENERATED**************************/////////////////////////////////
    #/////------START----------//////(DONOT EDIT UNTIL YOU KNOW WHAT YOU ARE DOING )
    def setupUi(self, NEW_WIN):
        
        NEW_WIN.setObjectName("NEW_WIN")
        NEW_WIN.setWindowModality(QtCore.Qt.ApplicationModal)
        NEW_WIN.resize(376, 243)
        NEW_WIN.setWindowFlag(Qt.FramelessWindowHint) ## THE LINE TO TITLE BAR
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(NEW_WIN)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Layout_TEAM_NAME = QtWidgets.QVBoxLayout()
        self.Layout_TEAM_NAME.setObjectName("Layout_TEAM_NAME")
        self.Label_Enter = QtWidgets.QLabel(NEW_WIN)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Enter.setFont(font)
        self.Label_Enter.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label_Enter.setIndent(103)
        self.Label_Enter.setObjectName("Label_Enter")
        self.Layout_TEAM_NAME.addWidget(self.Label_Enter)
        self.Label_TEAM_NAME = QtWidgets.QLabel(NEW_WIN)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.Label_TEAM_NAME.setFont(font)
        self.Label_TEAM_NAME.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label_TEAM_NAME.setIndent(78)
        self.Label_TEAM_NAME.setObjectName("Label_TEAM_NAME")
        self.Layout_TEAM_NAME.addWidget(self.Label_TEAM_NAME)
        spacerItem = QtWidgets.QSpacerItem(20, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.Layout_TEAM_NAME.addItem(spacerItem)

        self.VALUE_TEAM_NAME = QtWidgets.QLineEdit(NEW_WIN)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VALUE_TEAM_NAME.sizePolicy().hasHeightForWidth())
        self.VALUE_TEAM_NAME.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.VALUE_TEAM_NAME.setFont(font)
        self.VALUE_TEAM_NAME.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.VALUE_TEAM_NAME.setInputMask("")
        self.VALUE_TEAM_NAME.setAlignment(QtCore.Qt.AlignCenter)
        self.VALUE_TEAM_NAME.setObjectName("VALUE_TEAM_NAME")
        self.Layout_TEAM_NAME.addWidget(self.VALUE_TEAM_NAME)
        spacerItem1 = QtWidgets.QSpacerItem(20, 26, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.Layout_TEAM_NAME.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.Layout_TEAM_NAME)
        self.Layout_Options = QtWidgets.QHBoxLayout()
        self.Layout_Options.setObjectName("Layout_Options")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Layout_Options.addItem(spacerItem2)
        self.BTN_OK = QtWidgets.QPushButton(NEW_WIN)
        self.BTN_OK.setAutoDefault(True)
        self.BTN_OK.setDefault(False)
        self.BTN_OK.setObjectName("BTN_OK")
        self.Layout_Options.addWidget(self.BTN_OK)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Layout_Options.addItem(spacerItem3)
        self.BTN_CNCL = QtWidgets.QPushButton(NEW_WIN)
        self.BTN_CNCL.setAutoDefault(True)
        self.BTN_CNCL.setDefault(False)
        self.BTN_CNCL.setFlat(False)
        self.BTN_CNCL.setObjectName("BTN_CNCL")
        self.Layout_Options.addWidget(self.BTN_CNCL)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Layout_Options.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.Layout_Options)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)

        self.retranslateUi(NEW_WIN)
        QtCore.QMetaObject.connectSlotsByName(NEW_WIN)
        NEW_WIN.setTabOrder(self.BTN_OK, self.BTN_CNCL)
        #/////------END----------//////(DONOT EDIT UNTIL YOU KNOW WHAT YOU ARE DOING )

        ### SHORTCUT (ESC) TO QUIT THE MAIN APPLICATION
        QShortcut(QKeySequence('Esc'), NEW_WIN).activated.connect(NEW_WIN.close)

        ''' FUNCTIONS INITIALISATION '''
        self.BTN_OK.clicked.connect(self.on_submit)
        self.BTN_OK.clicked.connect(NEW_WIN.close)
        self.BTN_CNCL.clicked.connect(NEW_WIN.close)
        self.NEW_WIN = NEW_WIN
    
    def on_submit(self):
        "TO VALIDATE AND SEND THE TEAM NAME TO MAIN WINDOW"
        self.Text = self.VALUE_TEAM_NAME.text()
        if len(self.Text) == 0:
            self.Error('Enter the team name')
        elif not(self.Text.isalnum()) :
            self.Error('Team Name should not have SPACES and SPECIAL CHARACTERS')

        else:
            self.submitted.emit(self.Text)
    
        
    def closing(self):
        "TO CLOSE WINDOW FROM MAIN WINDOW"
        self.NEW_WIN.close()

    def Error(self,message):
        "CREATES WIDGET TO RAISE ERRORS IF ANY"
        self.func_widget = QtWidgets.QWidget()
        self.func_call = dialog_box()
        self.func_call.setupUi(self.func_widget,message)
        self.func_widget.show()

    #/////------START----------//////(DONOT EDIT UNTIL YOU KNOW WHAT YOU ARE DOING )
    def retranslateUi(self, NEW_WIN):
        _translate = QtCore.QCoreApplication.translate
        NEW_WIN.setWindowTitle(_translate("NEW_WIN", "NEW_TEAM"))
        self.Label_Enter.setText(_translate("NEW_WIN", "Enter the  "))
        self.Label_TEAM_NAME.setText(_translate("NEW_WIN", "Team Name  "))
        self.BTN_OK.setText(_translate("NEW_WIN", "Ok"))
        self.BTN_CNCL.setText(_translate("NEW_WIN", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NEW_WIN = QtWidgets.QDialog()
    ui = Ui_NEW_WIN()
    ui.setupUi(NEW_WIN)
    NEW_WIN.show()
    sys.exit(app.exec_())
#/////-----END----------//////(DONOT EDIT UNTIL YOU KNOW WHAT YOU ARE DOING )