# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OPEN_WIN.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys 

## FOR REMOVING TITLE BAR
from PyQt5.QtCore import Qt 

## FOR SHORTCUT 
from PyQt5.QtWidgets  import QShortcut
from PyQt5.QtGui import QKeySequence

## TO SEND THE DATA TO MAIN WINDOW
from PyQt5.QtCore import Qt , pyqtSlot , pyqtSignal

## For Database connectivity
import sqlite3

class Ui_OPEN_WIN(QtCore.QObject):
    ## object to send data 
    submitted = QtCore.pyqtSignal(str)
    #/////////////////////*********************QT DISGNER GENERATED**************************/////////////////////////////////
    #/////------START----------//////(DONOT EDIT UNTIL YOU KNOW WHAT YOU ARE DOING )
    def setupUi(self, OPEN_WIN):
        ## DATABASE INITIALISATION
        self.connect = sqlite3.connect('CricketFantasy.db2')
        self.cursor = self.connect.cursor()      

        
        OPEN_WIN.setObjectName("OPEN_WIN")
        OPEN_WIN.setWindowModality(QtCore.Qt.ApplicationModal)
        OPEN_WIN.resize(376, 243)

        OPEN_WIN.setWindowFlag(Qt.FramelessWindowHint) ## THE LINE TO THE TITLE BAR
        
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(OPEN_WIN)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Layout_TEAM_NAME = QtWidgets.QVBoxLayout()
        self.Layout_TEAM_NAME.setObjectName("Layout_TEAM_NAME")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.Layout_TEAM_NAME.addItem(spacerItem)
        self.Label_TEAM_NAME = QtWidgets.QLabel(OPEN_WIN)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.Label_TEAM_NAME.setFont(font)
        self.Label_TEAM_NAME.setIndent(76)
        self.Label_TEAM_NAME.setObjectName("Label_TEAM_NAME")
        self.Layout_TEAM_NAME.addWidget(self.Label_TEAM_NAME)
        spacerItem1 = QtWidgets.QSpacerItem(20, 12, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.Layout_TEAM_NAME.addItem(spacerItem1)
        self.ComboBox_SELECT_TEAM = QtWidgets.QComboBox(OPEN_WIN)
        self.ComboBox_SELECT_TEAM.setIconSize(QtCore.QSize(16, 16))
        self.ComboBox_SELECT_TEAM.setObjectName("ComboBox_SELECT_TEAM")
        self.Layout_TEAM_NAME.addWidget(self.ComboBox_SELECT_TEAM)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.Layout_TEAM_NAME.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.Layout_TEAM_NAME)
        self.Layout_Options = QtWidgets.QHBoxLayout()
        self.Layout_Options.setObjectName("Layout_Options")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Layout_Options.addItem(spacerItem3)
        self.BTN_OK = QtWidgets.QPushButton(OPEN_WIN)
        self.BTN_OK.setAutoDefault(True)
        self.BTN_OK.setDefault(False)
        self.BTN_OK.setObjectName("BTN_OK")
        self.Layout_Options.addWidget(self.BTN_OK)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Layout_Options.addItem(spacerItem4)
        self.BTN_CNCL = QtWidgets.QPushButton(OPEN_WIN)
        self.BTN_CNCL.setAutoDefault(True)
        self.BTN_CNCL.setDefault(False)
        self.BTN_CNCL.setFlat(False)
        self.BTN_CNCL.setObjectName("BTN_CNCL")
        self.Layout_Options.addWidget(self.BTN_CNCL)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Layout_Options.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.Layout_Options)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.retranslateUi(OPEN_WIN)
        
        QtCore.QMetaObject.connectSlotsByName(OPEN_WIN)
        OPEN_WIN.setTabOrder(self.ComboBox_SELECT_TEAM, self.BTN_OK)
        OPEN_WIN.setTabOrder(self.BTN_OK, self.BTN_CNCL)
        #/////------END----------//////(DONOT EDIT UNTIL YOU KNOW WHAT YOU ARE DOING )

        ''' MAKING SHORTCUT FOR CLOSING WINDOW (ESC) '''
        QShortcut(QKeySequence('Esc'), OPEN_WIN).activated.connect(OPEN_WIN.close)

        ''' FUNCTIONS INITIALISATION '''
        self.Get_Names() ## COMBOX INITIALISATION
        self.BTN_OK.clicked.connect(self.Selected_team) ## TO SEND DATA WHEN OK BUTTON CLICKED
        self.BTN_CNCL.clicked.connect(OPEN_WIN.close)
        
        self.OPEN_WIN = OPEN_WIN # FOR CLOSING WINDOW FROM MAIN

    def closing(self):
        "TO CLOSE WINDOW FROM MAIN WINDOW"
        self.OPEN_WIN.close()

    def Selected_team(self):
        "THE PYSIGNAL TO SEND THE DATA TO MAIN WINDOW"
        self.Team_name = self.Team_Names[self.ComboBox_SELECT_TEAM.currentIndex()]
        self.submitted.emit(self.Team_name)
        self.OPEN_WIN.close()
        
    
    def Get_Names(self):
        "TO ADD THE TEAM NAMES TO COMBO BOX "
        self.cursor.execute("SELECT DISTINCT NAME FROM TEAMS;")
        self.team_names = self.cursor.fetchall()
        self.Team_Names= [ i[0] for i in self.team_names ]
        for i in self.Team_Names:
            self.ComboBox_SELECT_TEAM.addItem(i)


    #/////------START----------//////(DONOT EDIT UNTIL YOU KNOW WHAT YOU ARE DOING )
    def retranslateUi(self, OPEN_WIN):
        _translate = QtCore.QCoreApplication.translate
        OPEN_WIN.setWindowTitle(_translate("OPEN_WIN", "OPEN_TEAM"))
        self.Label_TEAM_NAME.setText(_translate("OPEN_WIN", "Team Name "))
        self.BTN_OK.setText(_translate("OPEN_WIN", "Ok"))
        self.BTN_CNCL.setText(_translate("OPEN_WIN", "Cancel"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    OPEN_WIN = QtWidgets.QDialog()
    ui = Ui_OPEN_WIN()
    ui.setupUi(OPEN_WIN)
    OPEN_WIN.show()
    sys.exit(app.exec_())
#/////------START----------//////(DONOT EDIT UNTIL YOU KNOW WHAT YOU ARE DOING )