# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'msgbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets 
import sys

## FOR FRAMELESS WINDOWS
from PyQt5.QtCore import Qt

## FOR SHORTCUT 
from PyQt5.QtWidgets  import QShortcut  
from PyQt5.QtGui import QKeySequence

## For Database connectivity
import sqlite3


class Ui_Form(object):
    #/////////////////////*********************QT DISGNER GENERATED**************************/////////////////////////////////
    #/////------START----------//////(DONOT EDIT UNTIL YOU KNOW WHAT YOU ARE DOING )
    def setupUi(self, Form,*args):
        ## Connecting database
        self.connect = sqlite3.connect('CricketFantasy.db2')
        self.cursor = self.connect.cursor()

        self.args = args
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(360, 157)
        Form.setStyleSheet("background-color: rgb(188, 188, 188);")
        Form.setWindowFlag(Qt.FramelessWindowHint) #----- LINE FOR FRAMELESS WINDOWS
        self.LABEL_PIC = QtWidgets.QLabel(Form)
        self.LABEL_PIC.setGeometry(QtCore.QRect(10, 10, 41, 51))
        self.LABEL_PIC.setText("")
        self.LABEL_PIC.setPixmap(QtGui.QPixmap("close-ico3n.png"))
        self.LABEL_PIC.setObjectName("LABEL_PIC")
        self.OK_BTN = QtWidgets.QPushButton(Form)
        self.OK_BTN.setGeometry(QtCore.QRect(140, 120, 75, 23))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.OK_BTN.setFont(font)
        self.OK_BTN.setStyleSheet("font: 12pt \"MV Boli\";")
        self.OK_BTN.setObjectName("OK_BTN")
        self.VALU_TEXT = QtWidgets.QTextBrowser(Form)
        self.VALU_TEXT.setGeometry(QtCore.QRect(50, 40, 291, 61))
        self.VALU_TEXT.setStyleSheet("font: 15pt \"MV Boli\"; border: 0")
        self.VALU_TEXT.setObjectName("VALU_TEXT")
        self.VALU_TEXT.setReadOnly(True)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        #/////------END----------//////(DONOT EDIT UNTIL YOU KNOW WHAT YOU ARE DOING )

        
        ## FOR QUIT THE WINDOW WITH THE LABEL
        self.LABEL_PIC.mousePressEvent = self.func_close ## func_close WAS CREATED AS lambda WAS ENABLE TO HANDLE THE ARGUMENTS 


        ### SHORTCUT (ESC) TO QUIT THE MAIN APPLICATION
        QShortcut(QKeySequence('Esc'), Form).activated.connect(lambda :Form.close())

        ## ## fOR THE MESSAGE ON THE WINDOW ( DIALOG BOX )
        self.Message_raise()
        self.Form = Form    

    def save_data(self):
        "USED TO SAVE THE DATA TO DATABASE"
        self.players = ""
        self.value = ""
        lst_players = []
        dic_players = self.args[1]
        self.team_name = self.args[2]
        for i in dic_players:
            for j in dic_players[i]:
                lst_players += [j,]
        for i in lst_players:
            self.cursor.execute("SELECT VALUE FROM STATS WHERE PLAYER = '"+i+"';")
            points = self.cursor.fetchall()[0][0]
            self.value += str(points)+" "
            self.players += str(i)+" "
        self.cursor.execute("SELECT DISTINCT NAME FROM TEAMS;")
        al_teams = self.cursor.fetchall()[0]
        for i in al_teams:
            if i==self.team_name:
                self.cursor.execute("DELETE FROM TEAMS WHERE NAME = '"+self.team_name+"';")
                self.connect.commit()
        self.cursor.execute('INSERT INTO TEAMS VALUES("'+self.team_name+'","'+self.players+'","'+self.value+'");')
        self.connect.commit()
        return 1
            
    def Message_raise(self):
        "USED TO  RAISE USER ERRORS AND SAVE DATA "
        save_revert = "Details Saved Succesfully"
        
        if self.args[0] == save_revert:
            if self.save_data():
                self.VALU_TEXT.setText(self.args[0])
            else:
                self.VALU_TEXT.setText("The Data was Not Saved Due To Some Database error")
        else:
            self.VALU_TEXT.setText(self.args[0])
        
        self.OK_BTN.clicked.connect(self.func_close)


    def func_close(self,*args):
        "THESE WAS CREATED TO CLOSE THE WINDOW AND HANDLE SOME ERRORS WHEN CALLED"
        self.Form.close()
    
    #/////------START----------//////(DONOT EDIT UNTIL YOU KNOW WHAT YOU ARE DOING )
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.VALU_TEXT.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.OK_BTN.setText(_translate("Form", "OK"))
        


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QDialog()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
#/////------END----------//////(DONOT EDIT UNTIL YOU KNOW WHAT YOU ARE DOING )